"""rolelevel

Revision ID: 24b119e8a083
Revises: cc869b12d7da
Create Date: 2023-09-05 15:15:04.642123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b119e8a083'
down_revision: Union[str, None] = 'cc869b12d7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'level')
    # ### end Alembic commands ###
